# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    ora_profile: "#{source_dir}"
  forge_modules:
    easy_type:              enterprisemodules/easy_type
    ora_install:            enterprisemodules/ora_install
    ora_cis:                enterprisemodules/ora_cis
    ora_config:             enterprisemodules/ora_config
    stdlib:                 puppetlabs/stdlib
    echo:                   ipcrm/echo
    archive:                puppet/archive
    augeasproviders_core:   herculesteam-augeasproviders_core
    augeasproviders_sysctl: herculesteam-augeasproviders_sysctl
    limits:                 saz/limits
    firewall:               puppetlabs-firewall
    firewalld:              crayfishx-firewalld
