# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    ora_profile: "#{source_dir}"
  repositories:
    easy_type:              git@github.com:enterprisemodules/easy_type.git
    ora_install:            git@github.com:enterprisemodules/ora_install.git
    ora_config:             git@github.com:enterprisemodules/ora_config.git
    ora_cis:                git@github.com:enterprisemodules/ora_cis.git
  forge_modules:
    powershell:             puppetlabs/powershell
    stdlib:                 puppetlabs/stdlib
    echo:                   ipcrm/echo
    archive:                puppet/archive
    augeasproviders_core:   herculesteam-augeasproviders_core
    augeasproviders_sysctl: herculesteam-augeasproviders_sysctl
    limits:                 saz/limits
    firewall:               puppetlabs-firewall
    firewalld:              crayfishx-firewalld
